# Generated by Django 2.0 on 2021-09-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewApplicantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interview_ID', models.IntegerField()),
                ('Interviewer', models.IntegerField()),
                ('SCHEDULE_TIMESTAMP', models.DateField(help_text='yyyy-mm-dd')),
                ('Applicant_id', models.IntegerField()),
                ('Result', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer_LoginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=30)),
                ('PASSWORD', models.CharField(max_length=30)),
            ],
        ),
    ]
