# Generated by Django 2.0 on 2021-09-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddingDetailsModel',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=30, unique=True)),
                ('DATE_OF_BIRTH', models.DateField(help_text='yyyy-mm-dd')),
                ('EMAIL', models.EmailField(max_length=30)),
                ('GENDER', models.CharField(max_length=30)),
                ('MOBILE', models.IntegerField()),
                ('ADDRESS', models.CharField(max_length=30)),
                ('USERNAME', models.CharField(max_length=30)),
                ('PASSWORD', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=30)),
                ('PASSWORD', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=30, unique=True)),
                ('DATE_OF_BIRTH', models.DateField(help_text='yyyy-mm-dd')),
                ('EMAIL', models.EmailField(max_length=30)),
                ('GENDER', models.CharField(max_length=30)),
                ('MOBILE', models.IntegerField()),
                ('QUALIFICATION', models.CharField(max_length=30)),
                ('POST', models.FloatField()),
                ('PERCENTAGE', models.FloatField()),
                ('RESUME', models.FileField(upload_to='applicant_document')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant_ID', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('Schedule_Date', models.DateField(help_text='yyyy-mm-dd')),
            ],
        ),
    ]
